---
# Blog applications

version: '3.8'

x-configs:
  app:
    network:
      use_cloudmap: True

services:
  rproxy:
    image: 373709687836.dkr.ecr.eu-west-1.amazonaws.com/blog-app-01-rproxy:latest
    build:
      context: .
      dockerfile: ../reverse_proxy/Dockerfile
    ports:
      - 80:80
    deploy:
      replicas: 2
      resources:
        reservations:
          cpus: "0.25"
          memory: "64M"
        limits:
          cpus: "0.25"
          memory: "128M"
      labels:
        - "ecs.task.family=app01"
    x-configs:
      network:
        is_public: True
        lb_type: application
    depends_on:
      - app
  app:
    image: 373709687836.dkr.ecr.eu-west-1.amazonaws.com/blog-app-01:profiler
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000
    deploy:
      resources:
        reservations:
          cpus: "0.25"
          memory: "128M"
        limits:
          cpus: "0.5"
          memory: "256M"
      labels:
        ecs.task.family: app01
    environment:
      LOGLEVEL: DEBUG
    x-configs:
      use_xray: True
    healthcheck:
      test:
        - CMD-SHELL
        - supervisorctl -c supervisord.config status
      retries: 1
